{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "tql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tql.selectorLabels" (dict "ctx" . "app" "web") | nindent 4 }}
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
{{- end }}
