{{- if eq (include "tql.secretsMode" .) "externalSecrets" }}
{{- $gcp := .Values.global.externalSecrets.gcp }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  labels:
    {{- include "tql.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ $gcp.projectId | quote }}
      {{- if $gcp.serviceAccountRef }}
      auth:
        workloadIdentity:
          clusterLocation: {{ $gcp.clusterLocation | quote }}
          clusterName: {{ $gcp.clusterName | quote }}
          serviceAccountRef:
            name: {{ $gcp.serviceAccountRef | quote }}
      {{- end }}
{{- end }}
