{{- if eq (include "tql.secretsMode" .) "externalSecrets" }}
{{- $p := include "tql.externalSecretsPrefix" . }}
{{ include "tql.externalSecretHeader" (dict "name" "sandbox-proxy-secrets" "root" .) }}
    - secretKey: ca.key
      remoteRef:
        key: {{ $p }}-sandbox-proxy-ca-key
{{- end }}
