{{- if .Values.computeEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sandbox-forward-proxy
  labels:
    {{- include "tql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tql.selectorLabels" (dict "ctx" . "app" "compute-engine") | nindent 4 }}
  ports:
    - name: tcp-proxy
      port: 8123
      targetPort: 8123
  type: ClusterIP
{{- end }}
