{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-data
  labels:
    {{- include "tql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
  {{- with .Values.postgres.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
