{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    {{- include "tql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
  selector:
    {{- include "tql.selectorLabels" (dict "ctx" . "app" "minio") | nindent 4 }}
{{- end }}
